### ISSUE TITLE
Is there an alternative way of defining the path to the templates?

### ISSUE THREAD

**Issue by mjemerson** [maantje/laravel-react-email#1]
Hi,

I was wondering if there's another way to set the path to where the templates are located in the project, as I'm not a fan of using absolute paths. Will a relative path work instead?

**Comment by maantje** [comment]
Hey @mjemerson,

That should be possible. You can publish the configuration file with `php artisan vendor:publish` and then selecting the ReactEmailServiceProvider.

In your config directory you should then see a `react-email.php` configuration file. In here you can make it relative, see below as an example to make it relative to base path.

```
<?php

return [
    'template_directory' =>  base_path(env('REACT_EMAIL_DIRECTORY')),
];
```
