### ISSUE TITLE
How to use env variable in tsx file?

### ISSUE THREAD

**Issue by rochmadnf** [maantje/laravel-react-email#8]

**Comment by Cold-A-Muse** [comment]
Just pass it to the __construct e.g.  `public function __construct(public User $user, public string $envVariableHere)` when you initialize an instance of your ReactMailable class. It should automatically be available in the props of your email react component :)

**Comment by maantje** [comment]
Hey @rochmadnf ,

What @Cold-A-Muse said is correct. It works like any other variable. But be careful when using the `env()` helper in your code; this will return `null` when caching your config. Preferably, you want to use `env()` in your config and then use `config()` to pass the value to your constructor.
